site_name: MOOSE.jl
pages:
    - Home: index.md
    - Installation: installation.md
    - Systems: systems.md
    - Examples:
        - 1. Laplacian: examples/laplacian.md
        - 2. Auto-Diff: examples/auto_diff.md
        - 3. PETSc: examples/petsc.md
        - 4. Parallel: examples/parallel.md